; Listing generated by Microsoft (R) Optimizing Compiler Version 19.31.31107.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	main
pdata	SEGMENT
$pdata$main DD	imagerel $LN5
	DD	imagerel $LN5+33
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	02204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$ = 0
main	PROC
; File F:\Dev\Projects\Things\test\test.cpp
; Line 4
$LN5:
	sub	rsp, 24
; Line 5
	mov	DWORD PTR i$[rsp], 1
; Line 7
	cmp	DWORD PTR i$[rsp], 1
	jne	SHORT $LN2@main
; Line 9
	xor	eax, eax
	jmp	SHORT $LN1@main
; Line 10
	jmp	SHORT $LN3@main
$LN2@main:
; Line 13
	mov	eax, 1
$LN3@main:
$LN1@main:
; Line 15
	add	rsp, 24
	ret	0
main	ENDP
_TEXT	ENDS
END
